In [1]:
# standard import
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
hd=pd.read_csv("heart-disease.csv.csv")
hd.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
from sklearn.model_selection import train_test_split
X = hd.drop(["target"],axis=1)
y =hd["target"]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [4]:
np.random.seed(4)
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)
rfc.score(X_test,y_test)

0.8524590163934426

In [5]:
## now wae are going to use the prediction to predict the results
y_preds = rfc.predict(X_test)

In [6]:
y_preds


array([0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0], dtype=int64)

In [7]:
# now we can compare the truth values in y_preds and y_test 

np.mean(y_preds == y_test)

0.8524590163934426

In [8]:
rfc.score(X_test,y_test)

0.8524590163934426

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_preds)

0.8524590163934426

# the above are the three different methods to evaluate the prediction and acutal values

In [10]:
# now we are going to use the predict_proba this method is used only for classification problems

y_probability = rfc.predict_proba(X_test)
y_probability

array([[0.86, 0.14],
       [0.14, 0.86],
       [0.91, 0.09],
       [0.98, 0.02],
       [0.04, 0.96],
       [0.01, 0.99],
       [0.17, 0.83],
       [0.11, 0.89],
       [0.04, 0.96],
       [0.77, 0.23],
       [0.96, 0.04],
       [0.23, 0.77],
       [0.56, 0.44],
       [0.47, 0.53],
       [0.24, 0.76],
       [1.  , 0.  ],
       [0.92, 0.08],
       [0.16, 0.84],
       [0.23, 0.77],
       [0.29, 0.71],
       [0.46, 0.54],
       [0.75, 0.25],
       [0.87, 0.13],
       [0.86, 0.14],
       [0.56, 0.44],
       [0.18, 0.82],
       [0.88, 0.12],
       [0.86, 0.14],
       [0.38, 0.62],
       [0.22, 0.78],
       [0.84, 0.16],
       [0.39, 0.61],
       [0.96, 0.04],
       [0.4 , 0.6 ],
       [0.93, 0.07],
       [0.47, 0.53],
       [0.05, 0.95],
       [0.45, 0.55],
       [0.27, 0.73],
       [0.87, 0.13],
       [0.81, 0.19],
       [0.96, 0.04],
       [0.34, 0.66],
       [0.92, 0.08],
       [1.  , 0.  ],
       [0.63, 0.37],
       [0.69, 0.31],
       [0.58,

## now lets compare the predict() and predict_proba()

In [11]:
rfc.predict(X_test[:5])

array([0, 1, 0, 0, 1], dtype=int64)

In [12]:
rfc.predict_proba(X_test[:5])

array([[0.86, 0.14],
       [0.14, 0.86],
       [0.91, 0.09],
       [0.98, 0.02],
       [0.04, 0.96]])

## now lets try it out for the regression problem

In [13]:
from sklearn.datasets import load_boston
boston = load_boston()
boston_df = pd.DataFrame(boston["data"],columns=boston["feature_names"])
boston_df["target"]=pd.Series(boston["target"])

In [14]:
X= boston_df.drop("target",axis=1)
y=boston_df["target"]
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [15]:
np.random.seed(3)
from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor()
clf.fit(X_train,y_train)
clf.score(X_test,y_test)

0.818500443617394

In [16]:
y_preds_for_regression = clf.predict(X_test)
y_preds_for_regression

array([20.58 , 20.489, 33.39 , 43.917, 34.874, 30.402, 21.99 , 15.579,
       32.534, 19.519, 24.107, 23.545, 17.817,  9.628, 13.842, 32.538,
       24.007, 14.347, 24.407, 13.545, 34.009, 14.787, 20.645, 18.87 ,
       23.338, 20.315, 48.598, 45.426, 16.008, 14.811, 17.095, 29.563,
       26.894, 20.555, 29.263, 20.291, 35.748, 17.214, 13.337, 24.969,
       20.288, 20.557, 12.745, 13.096, 20.469, 23.176, 27.12 , 20.988,
       26.413, 34.144, 41.201, 23.809, 34.146, 24.521, 11.998, 27.904,
       20.27 , 31.372, 15.085, 23.234, 15.424, 19.321, 19.873, 44.29 ,
       18.464, 20.538, 18.629, 25.011, 33.711, 19.946, 29.972, 25.799,
       11.261, 32.216, 25.954, 31.7  , 20.834, 20.522, 14.52 , 26.336,
       20.111, 15.468, 46.751, 17.581, 20.943, 14.887, 20.109, 11.751,
        9.973, 28.597, 14.881, 11.595, 44.507, 16.065, 12.584, 19.948,
       19.681, 29.21 , 15.44 , 27.065, 14.036, 19.474])

In [17]:
np.array(y_test[:10])

array([19. , 21.2, 29. , 43.1, 33.2, 41.3, 22. , 17.8, 33.2, 17.4])

In [18]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test,y_preds_for_regression)

2.3545392156862746